Repository lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu, pull requests merged in 2024-10, with the labels that each got.

#6 TASK-1
  anton.piyavkin/task-1/cmd/service/main.go
  anton.piyavkin/task-1/go.mod
Labels: Approved

#23 TASK-1
  maksim.kladkovoj/task-1/cmd/service/main.go
  maksim.kladkovoj/task-1/go.mod
Labels: Approved

#12 TASK-1
  elina.klebleeva/task-1/cmd/service/main.go
  elina.klebleeva/task-1/go.mod
  elina.klebleeva/task-1/internal/calculation/calculation.go
  elina.klebleeva/task-1/internal/input/input.go
  elina.klebleeva/task-1/pkg/operations/operations.go
Labels: Approved

#11 TASK-1
  ann.kozakova/task-1/cmd/service/main.go
  ann.kozakova/task-1/go.mod
Labels: Approved

#37 TASK-1
  khudyakov.gennady/task-1/cmd/service/main.go
  khudyakov.gennady/task-1/go.mod
Labels: Approved

#54 TASK-1
  kirill.romanchuk/task-1/cmd/service/main.go
  kirill.romanchuk/task-1/go.mod
Labels: Approved

#3 TASK-1
  matvey.shmonov/task-1/cmd/service/main.go
  matvey.shmonov/task-1/go.mod
Labels: Approved

#78 TASK-1
  danil.novokhatskiy/task-1/cmd/service/main.go
  danil.novokhatskiy/task-1/go.mod
Labels: Approved

#76 TASK-2-1
  elina.klebleeva/task-2-1/cmd/service/main.go
  elina.klebleeva/task-2-1/go.mod
  elina.klebleeva/task-2-1/internal/calculation/calculation.go
  elina.klebleeva/task-2-1/internal/input/input.go
Labels: Approved

#75 TASK-1
  nikita.bogdanov/task-1/cmd/service/main.go
  nikita.bogdanov/task-1/go.mod
  nikita.bogdanov/task-1/internal/BigComplex.go
  nikita.bogdanov/task-1/internal/calculator.go
  nikita.bogdanov/task-1/internal/interpetator.go
Labels: Approved

#74 TASK-2-2
  pavel.kalabin/task-2-2/cmd/service/main.go
  pavel.kalabin/task-2-2/go.mod
  pavel.kalabin/task-2-2/internal/dishes/dishes.go
  pavel.kalabin/task-2-2/internal/inputErrors/inputErrors.go
Labels: Approved

#71 TASK-2-1
  pavel.kalabin/task-2-1/cmd/service/main.go
  pavel.kalabin/task-2-1/errors/operation/operationError.go
  pavel.kalabin/task-2-1/errors/temperature/temperatureError.go
  pavel.kalabin/task-2-1/go.mod
  pavel.kalabin/task-2-1/util/condition/condition.go
Labels: Approved

#64 TASK-1
  alex.udalov/task-1/cmd/service/main.go
  alex.udalov/task-1/go.mod
Labels: Approved

#63 TASK-2-2
  elina.klebleeva/task-2-2/cmd/service/main.go
  elina.klebleeva/task-2-2/go.mod
  elina.klebleeva/task-2-2/internal/findDish/findDish.go
  elina.klebleeva/task-2-2/internal/input/input.go
  elina.klebleeva/task-2-2/internal/myErrors/inputError/inputError.go
  elina.klebleeva/task-2-2/pkg/heapInt/HeapInt.go
Labels: Approved

#62 TASK-1
  andrey.kostin/task-1/cmd/service/main.go
  andrey.kostin/task-1/go.mod
  andrey.kostin/task-1/internal/operations/operations.go
Labels: Approved

#61 TASK-1
  alina.mamonova/task-1/cmd/service/main.go
  alina.mamonova/task-1/go.mod
Labels: Approved

#57 TASK-2-1
  mark.zheleznyakov/task-2-1/cmd/service/main.go
  mark.zheleznyakov/task-2-1/go.mod
  mark.zheleznyakov/task-2-1/internal/input/read.go
Labels: Approved

#56 TASK-2-2
  matvey.shmonov/task-2-2/cmd/service/main.go
  matvey.shmonov/task-2-2/go.mod
  matvey.shmonov/task-2-2/internal/structure/heap.go
Labels: Approved

#79 TASK-2-1
  andrey.kostin/task-2-1/cmd/service/main.go
  andrey.kostin/task-2-1/go.mod
  andrey.kostin/task-2-1/internal/bounds/bounds.go
  andrey.kostin/task-2-1/internal/errors/errors.go
  andrey.kostin/task-2-1/internal/io/io.go
Labels: Approved

#51 TASK-2-2
  anton.piyavkin/task-2-2/cmd/service/main.go
  anton.piyavkin/task-2-2/go.mod
  anton.piyavkin/task-2-2/internal/getDish/getKDish.go
  anton.piyavkin/task-2-2/internal/myHeap/heap.go
Labels: Approved

#50 TASK-2-1
  anton.piyavkin/task-2-1/cmd/service/main.go
  anton.piyavkin/task-2-1/go.mod
  anton.piyavkin/task-2-1/internal/input/readInt.go
  anton.piyavkin/task-2-1/internal/output/writeInt.go
  anton.piyavkin/task-2-1/internal/temp/getTemp.go
Labels: Approved

#22 TASK-1
  sofia.dudkina/task-1/cmd/service/main.go
  sofia.dudkina/task-1/go.mod
Labels: Approved

#33 TASK-2-2
  gleb.madyarov/task-2-2/cmd/service/main.go
  gleb.madyarov/task-2-2/go.mod
  gleb.madyarov/task-2-2/internal/iheap/iheap.go
  gleb.madyarov/task-2-2/internal/input/inputValues.go
  gleb.madyarov/task-2-2/internal/solving/findK.go
Labels: Approved

#31 TASK-1
  gleb.madyarov/task-1/cmd/service/main.go
  gleb.madyarov/task-1/go.mod
Labels: Approved

#17 TASK-2-1
  ann.kozakova/task-2-1/cmd/service/main.go
  ann.kozakova/task-2-1/go.mod
  ann.kozakova/task-2-1/internal/temp/temp.go
Labels: Approved

#18 TASK-2-2
  ann.kozakova/task-2-2/cmd/service/main.go
  ann.kozakova/task-2-2/go.mod
  ann.kozakova/task-2-2/internal/data/enter_data.go
  ann.kozakova/task-2-2/internal/max/find_max.go
  ann.kozakova/task-2-2/pkg/int_heap/int_heap.go
Labels: Approved

#8 TASK-1
  zhukov.gleb/task-1/cmd/service/main.go
  zhukov.gleb/task-1/go.mod
Labels: Changes required

#36 TASK-1
  yakov.poluektov/task-1/cmd/service/main.go
  yakov.poluektov/task-1/go.mod
  yakov.poluektov/task-1/internal/calculator/console.go
Labels: Approved

#52 TASK-2-1
  matvey.shmonov/task-2-1/cmd/service/main.go
  matvey.shmonov/task-2-1/go.mod
  matvey.shmonov/task-2-1/internal/temperature/temperature.go
Labels: Approved

#70 TASK-2-2
  mark.zheleznyakov/task-2-2/cmd/service/main.go
  mark.zheleznyakov/task-2-2/go.mod
  mark.zheleznyakov/task-2-2/internal/dishesHeap/heap.go
  mark.zheleznyakov/task-2-2/internal/read/read.go
Labels: Approved

#58 TASK-2-2
  mesropyan.artyom/task-2-2/chooseDish/chooseDish.go
  mesropyan.artyom/task-2-2/cmd/task-2-2/caffe.go
  mesropyan.artyom/task-2-2/go.mod
  mesropyan.artyom/task-2-2/myHeap/myHeap.go
  mesropyan.artyom/task-2-2/readDishes/readDishes.go
Labels: Approved

#65 TASK-2-1
  anastasiya.soboleva/task-2-1/cmd/service/main.go
  anastasiya.soboleva/task-2-1/go.mod
  anastasiya.soboleva/task-2-1/internal/reader/reader.go
  anastasiya.soboleva/task-2-1/internal/temperature/temperature.go
Labels: Approved

#24 TASK-2-1
  maksim.kladkovoj/task-1/cmd/service/main.go
  maksim.kladkovoj/task-1/go.mod
  maksim.kladkovoj/task-2-1/cmd/service/main.go
  maksim.kladkovoj/task-2-1/go.mod
  maksim.kladkovoj/task-2-1/internal/calculate/calculate.go
  maksim.kladkovoj/task-2-1/internal/input/addTemp.go
  maksim.kladkovoj/task-2-1/internal/input/error.go
Labels: Questions?)

#34 TASK-1
  mesropyan.artyom/task-1/cmd/service/task-1.go
  mesropyan.artyom/task-1/go.mod
Labels: Approved

#81 TASK-2-2
  andrey.kostin/task-2-2/cmd/service/main.go
  andrey.kostin/task-2-2/go.mod
  andrey.kostin/task-2-2/internal/dishHeap/dishHeap.go
  andrey.kostin/task-2-2/internal/errors/errors.go
  andrey.kostin/task-2-2/internal/findDish/findDish.go
  andrey.kostin/task-2-2/internal/io/io.go
Labels: Approved

#60 TASK-2-2
  erdem.istaev/task-2-2/cmd/service/main.go
  erdem.istaev/task-2-2/go.mod
  erdem.istaev/task-2-2/internal/findkmax/k_max.go
  erdem.istaev/task-2-2/internal/input/read.go
  erdem.istaev/task-2-2/internal/structure/IntHeap.go
Labels: Approved

#59 TASK-2-1
  erdem.istaev/task-2-1/cmd/service/main.go
  erdem.istaev/task-2-1/go.mod
  erdem.istaev/task-2-1/internal/comparsion/min_max.go
  erdem.istaev/task-2-1/internal/input/errors.go
  erdem.istaev/task-2-1/internal/input/read_symbols.go
  erdem.istaev/task-2-1/internal/structure/temperature_bounds.go
Labels: Changes required, Questions?)

#87 TASK-2-1
  alex.udalov/task-2-1/cmd/service/main.go
  alex.udalov/task-2-1/go.mod
  alex.udalov/task-2-1/internal/analyzer/analyzer.go
  alex.udalov/task-2-1/internal/temperature/temperature.go
Labels: Approved

#82 TASK-2-1
  danil.novokhatskiy/task-2-1/cmd/service/main.go
  danil.novokhatskiy/task-2-1/go.mod
  danil.novokhatskiy/task-2-1/internal/computeTemperature.go
  danil.novokhatskiy/task-2-1/internal/errors.go
  danil.novokhatskiy/task-2-1/internal/readAndOutputData.go
Labels: Changes required

#42 TASK-2-2
  sofia.dudkina/task-2-2/cmd/service/main.go
  sofia.dudkina/task-2-2/go.mod
  sofia.dudkina/task-2-2/internal/data/input.go
  sofia.dudkina/task-2-2/internal/data/output.go
  sofia.dudkina/task-2-2/pkg/iheap/iheap.go
  sofia.dudkina/task-2-2/pkg/maxk/maxk.go
Labels: Approved

#41 TASK-2-1
  sofia.dudkina/task-2-1/cmd/service/main.go
  sofia.dudkina/task-2-1/go.mod
  sofia.dudkina/task-2-1/internal/optimalt/optimalt.go
Labels: Approved

#32 TASK-2-1
  gleb.madyarov/task-2-1/cmd/service/main.go
  gleb.madyarov/task-2-1/go.mod
  gleb.madyarov/task-2-1/internal/input/inputTemp.go
  gleb.madyarov/task-2-1/internal/output/outAnswer.go
Labels: Approved

#88 TASK-2-1
  nikita.bogdanov/task-2-1/cmd/service/main.go
  nikita.bogdanov/task-2-1/go.mod
  nikita.bogdanov/task-2-1/internal/app/app.go
  nikita.bogdanov/task-2-1/internal/reader/data_reader.go
  nikita.bogdanov/task-2-1/internal/writer/data_writer.go
Labels: Approved

#89 TASK-2-2
  nikita.bogdanov/task-2-2/cmd/service/main.go
  nikita.bogdanov/task-2-2/go.mod
  nikita.bogdanov/task-2-2/internal/app/app.go
  nikita.bogdanov/task-2-2/internal/heap/heap.go
  nikita.bogdanov/task-2-2/internal/reader/data_reader.go
Labels: Approved

#83 TASK-2-2
  zhukov.gleb/task-2-2/cmd/main.go
  zhukov.gleb/task-2-2/go.mod
  zhukov.gleb/task-2-2/internal/heap/heap.go
  zhukov.gleb/task-2-2/internal/lunch/lunch.go
  zhukov.gleb/task-2-2/internal/reader/reader.go
Labels: Changes required

#84 TASK-2-1
  zhukov.gleb/task-2-1/cmd/main.go
  zhukov.gleb/task-2-1/go.mod
  zhukov.gleb/task-2-1/internal/control/control.go
  zhukov.gleb/task-2-1/internal/reader/reader.go
Labels: Changes required
