Repository lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu, pull requests merged in 2024-11, with the labels that each got.

#92 TASK-3
  ann.kozakova/task-3/cmd/service/main.go
  ann.kozakova/task-3/config/config.yml
  ann.kozakova/task-3/go.mod
  ann.kozakova/task-3/go.sum
  ann.kozakova/task-3/internal/encoding/json_encoding.go
  ann.kozakova/task-3/internal/encoding/output_file.go
  ann.kozakova/task-3/internal/flag/config_flag.go
  ann.kozakova/task-3/internal/parsing/config_parsing.go
  ann.kozakova/task-3/internal/parsing/input_parsing.go
  ann.kozakova/task-3/internal/structures/config_struct.go
  ann.kozakova/task-3/internal/structures/valcurs_struct.go
  ann.kozakova/task-3/internal/structures/valute_struct.go
  ann.kozakova/task-3/internal/structures/valuteinjson_struct.go
Labels: Approved

#98 TASK-3
  anton.piyavkin/task-3/cmd/service/main.go
  anton.piyavkin/task-3/go.mod
  anton.piyavkin/task-3/go.sum
  anton.piyavkin/task-3/internal/input/read.go
  anton.piyavkin/task-3/internal/input/sort.go
  anton.piyavkin/task-3/internal/output/write.go
  anton.piyavkin/task-3/internal/parse/config.go
  anton.piyavkin/task-3/internal/parse/flag.go
  anton.piyavkin/task-3/internal/structures/config.go
  anton.piyavkin/task-3/internal/structures/currencies.go
  anton.piyavkin/task-3/internal/structures/output_val.go
  anton.piyavkin/task-3/internal/structures/quotes.go
Labels: Approved

#91 TASK-3
  mark.zheleznyakov/task-3/cmd/service/main.go
  mark.zheleznyakov/task-3/go.mod
  mark.zheleznyakov/task-3/go.sum
  mark.zheleznyakov/task-3/internal/config/flags.go
  mark.zheleznyakov/task-3/internal/config/yaml.go
  mark.zheleznyakov/task-3/internal/currencies/converter.go
  mark.zheleznyakov/task-3/internal/currencies/parser.go
  mark.zheleznyakov/task-3/internal/currencies/sort.go
Labels: Changes required

#99 TASK-3
  zhukov.gleb/task-3/cmd/service/main.go
  zhukov.gleb/task-3/go.mod
  zhukov.gleb/task-3/go.sum
  zhukov.gleb/task-3/internal/controller/controller.go
  zhukov.gleb/task-3/internal/fileWorkers/fileWorkers.go
  zhukov.gleb/task-3/internal/structs/structs.go
Labels: Approved

#103 TASK-3
  elina.klebleeva/task-3/cmd/service/main.go
  elina.klebleeva/task-3/configs/configData/configData.go
  elina.klebleeva/task-3/go.mod
  elina.klebleeva/task-3/go.sum
  elina.klebleeva/task-3/internal/app/app.go
  elina.klebleeva/task-3/internal/errorUtils/errorUtils.go
  elina.klebleeva/task-3/internal/parseFlag/parseFlag.go
  elina.klebleeva/task-3/internal/parseXml/parseXml.go
  elina.klebleeva/task-3/internal/structs/xmlStruct/xmlStruct.go
  elina.klebleeva/task-3/internal/writeJson/writeJson.go
Labels: Approved

#85 TASK-2-1
  alina.mamonova/task-2-1/cmd/service/main.go
  alina.mamonova/task-2-1/go.mod
  alina.mamonova/task-2-1/internal/departments_handler/departments_handler.go
  alina.mamonova/task-2-1/internal/errors/errors.go
  alina.mamonova/task-2-1/internal/input/input.go
Labels: Approved

#86 TASK-2-2
  alina.mamonova/task-2-2/cmd/service/main.go
  alina.mamonova/task-2-2/go.mod
  alina.mamonova/task-2-2/internal/errors/errors.go
  alina.mamonova/task-2-2/internal/heap-handler/heap_handler.go
  alina.mamonova/task-2-2/internal/input/input.go
  alina.mamonova/task-2-2/internal/table-heap/table_heap.go
Labels: Approved

#119 TASK-2-2
  alex.udalov/task-2-2/cmd/service/main.go
  alex.udalov/task-2-2/go.mod
  alex.udalov/task-2-2/internal/meatHeap/meatHeap.go
  alex.udalov/task-2-2/internal/reader/reader.go
Labels: Approved

#108 TASK-4
  anastasiya.soboleva/task-4/cmd/service/main.go
  anastasiya.soboleva/task-4/go.mod
  anastasiya.soboleva/task-4/internal/exhibit/exhibit.go
  anastasiya.soboleva/task-4/internal/simulator/simulator.go
  anastasiya.soboleva/task-4/internal/visitorCounter/visitorCounter.go
Labels: Approved

#110 TASK-4
  danil.novokhatskiy/task-4/cmd/service/main.go
  danil.novokhatskiy/task-4/go.mod
  danil.novokhatskiy/task-4/internal/counter.go
Labels: Approved

#112 TASK-4
  sofia.dudkina/task-4/cmd/service/main.go
  sofia.dudkina/task-4/go.mod
  sofia.dudkina/task-4/internal/entity/store.go
  sofia.dudkina/task-4/internal/entity/unsafeStore.go
  sofia.dudkina/task-4/internal/test/UnsafeTest.go
  sofia.dudkina/task-4/internal/test/safeTest.go
Labels: Approved

#104 TASK-4
  ann.kozakova/task-4/cmd/service/main.go
  ann.kozakova/task-4/go.mod
  ann.kozakova/task-4/internal/shops/shop.go
Labels: Approved

#107 TASK-4
  elina.klebleeva/task-4/cmd/service/main.go
  elina.klebleeva/task-4/go.mod
  elina.klebleeva/task-4/internal/app/app.go
  elina.klebleeva/task-4/internal/interfaces/postSocialNet/postSocialNet.go
  elina.klebleeva/task-4/internal/parseFlag/parseFlag.go
  elina.klebleeva/task-4/internal/structs/postSocialNetSync/postSocialNetSync.go
  elina.klebleeva/task-4/internal/structs/postSocialNetUnsync/postSocialNetUnsync.go
Labels: Approved

#114 TASK-4
  gleb.madyarov/task-4/cmd/service/main.go
  gleb.madyarov/task-4/go.mod
  gleb.madyarov/task-4/internal/counter/counter.go
  gleb.madyarov/task-4/internal/test/test.go
Labels: Approved

#111 TASK-4
  mark.zheleznyakov/task-4/cmd/service/main.go
  mark.zheleznyakov/task-4/go.mod
  mark.zheleznyakov/task-4/internal/parking/parking.go
  mark.zheleznyakov/task-4/internal/simulation/simulation.go
  mark.zheleznyakov/task-4/internal/simulation/unsafe.go
Labels: Approved

#102 TASK-4
  zhukov.gleb/task-4/cmd/service/main.go
  zhukov.gleb/task-4/go.mod
  zhukov.gleb/task-4/pkg/metro/metro.go
  zhukov.gleb/task-4/pkg/metro/repo.go
  zhukov.gleb/task-4/pkg/unsafemetro/repo.go
  zhukov.gleb/task-4/pkg/unsafemetro/unsafemetro.go
Labels: Approved

#100 TASK-3
  danil.novokhatskiy/task-3/cmd/service/main.go
  danil.novokhatskiy/task-3/go.mod
  danil.novokhatskiy/task-3/go.sum
  danil.novokhatskiy/task-3/internal/converterData.go
  danil.novokhatskiy/task-3/internal/currencyAndXml.go
  danil.novokhatskiy/task-3/internal/parseYaml.go
  danil.novokhatskiy/task-3/internal/sorting.go
Labels: Questions?)

#93 TASK-3
  maksim.kladkovoj/task-3/cmd/service/main.go
  maksim.kladkovoj/task-3/go.mod
  maksim.kladkovoj/task-3/go.sum
  maksim.kladkovoj/task-3/internal/config/flag.go
  maksim.kladkovoj/task-3/internal/config/loadConf.go
  maksim.kladkovoj/task-3/internal/logic/convert.go
  maksim.kladkovoj/task-3/internal/logic/sort.go
  maksim.kladkovoj/task-3/internal/logic/writer.go
  maksim.kladkovoj/task-3/internal/run/run.go
  maksim.kladkovoj/task-3/internal/structures/config.go
  maksim.kladkovoj/task-3/internal/structures/valcurs.go
Labels: Approved, Changes required

#130 TASK-4
  alina.mamonova/task-4/cmd/service/main.go
  alina.mamonova/task-4/go.mod
  alina.mamonova/task-4/internal/counterStructs/safeCounterStruct.go
  alina.mamonova/task-4/internal/counterStructs/unsafeCounterStructs.go
  alina.mamonova/task-4/internal/tests/tests.go
Labels: Approved

#137 TASK-6
  anton.piyavkin/task-6/.golangci.yaml
  anton.piyavkin/task-6/cmd/db/main.go
  anton.piyavkin/task-6/cmd/wifi/main.go
  anton.piyavkin/task-6/go.mod
  anton.piyavkin/task-6/go.sum
  anton.piyavkin/task-6/internal/db/db_functions.go
  anton.piyavkin/task-6/internal/db/db_functions_test.go
  anton.piyavkin/task-6/internal/wifi/WiFi_test.go
  anton.piyavkin/task-6/internal/wifi/wi-fi.go
  anton.piyavkin/task-6/internal/wifi/wi-fi_test.go
Labels: Approved

#122 TASK-4
  maksim.kladkovoj/task-4/cmd/service/main.go
  maksim.kladkovoj/task-4/go.mod
  maksim.kladkovoj/task-4/internal/simulation/simulate.go
  maksim.kladkovoj/task-4/internal/simulation/unsafeSimulate.go
  maksim.kladkovoj/task-4/internal/structures/trainStruct.go
Labels: Approved

#120 TASK-4
  mesropyan.artyom/task-4/cmd/service/main.go
  mesropyan.artyom/task-4/cmd/unsafe/unsafe.go
  mesropyan.artyom/task-4/go.mod
  mesropyan.artyom/task-4/queue/queue.go
  mesropyan.artyom/task-4/queue/unsafeQueue.go
Labels: Approved

#129 TASK-4
  kirill.romanchuk/task-4/cmd/service/main.go
  kirill.romanchuk/task-4/go.mod
  kirill.romanchuk/task-4/structures/client/client.go
  kirill.romanchuk/task-4/structures/performance/performance.go
  kirill.romanchuk/task-4/utils/readers/readers.go
Labels: Approved

#121 TASK-3
  kirill.romanchuk/task-3/XML_daily.xml
  kirill.romanchuk/task-3/cmd/service/config.yaml
  kirill.romanchuk/task-3/cmd/service/main.go
  kirill.romanchuk/task-3/go.mod
  kirill.romanchuk/task-3/go.sum
  kirill.romanchuk/task-3/strtructs/config/config.go
  kirill.romanchuk/task-3/strtructs/currencyRates/currency.go
  kirill.romanchuk/task-3/strtructs/currencyRates/сurrencyRates.go
  kirill.romanchuk/task-3/test.json
Labels: Approved

#127 TASK-3
  alex.udalov/task-3/cmd/service/main.go
  alex.udalov/task-3/config.yaml
  alex.udalov/task-3/go.mod
  alex.udalov/task-3/go.sum
  alex.udalov/task-3/internal/config/config.go
  alex.udalov/task-3/internal/valuteProcessing/JSONparser.go
  alex.udalov/task-3/internal/valuteProcessing/XMLparser.go
  alex.udalov/task-3/internal/valuteProcessing/sorting.go
  alex.udalov/task-3/internal/valuteProcessing/writeResult.go
  alex.udalov/task-3/internal/valuteStrukts/valuteStrukts.go
  alex.udalov/task-3/source/input.xml
Labels: Changes required

#106 TASK-3
  anastasiya.soboleva/task-3/cmd/service/main.go
  anastasiya.soboleva/task-3/go.mod
  anastasiya.soboleva/task-3/go.sum
  anastasiya.soboleva/task-3/internal/models/config.go
  anastasiya.soboleva/task-3/internal/models/valute.go
  anastasiya.soboleva/task-3/internal/models/сurrency.go
  anastasiya.soboleva/task-3/internal/parser/convert.go
  anastasiya.soboleva/task-3/internal/parser/parseConfig.go
  anastasiya.soboleva/task-3/internal/parser/parseRates.go
  anastasiya.soboleva/task-3/internal/parser/parseXML.go
  anastasiya.soboleva/task-3/internal/sort/sort.go
  anastasiya.soboleva/task-3/internal/utils/fileUtils.go
  anastasiya.soboleva/task-3/internal/utils/output.go
Labels: Approved

#145 TASK-8
  elina.klebleeva/task-8/cmd/build/main.go
  elina.klebleeva/task-8/cmd/embed/config.json
  elina.klebleeva/task-8/cmd/embed/main.go
  elina.klebleeva/task-8/cmd/generate/main.go
  elina.klebleeva/task-8/cmd/generate/mocks/mock_database.go
  elina.klebleeva/task-8/cmd/tags/main_base.go
  elina.klebleeva/task-8/cmd/tags/main_pro.go
  elina.klebleeva/task-8/go.mod
  elina.klebleeva/task-8/go.sum
Labels: Approved

#155 TASK 7
  .github/workflows/artyom_mesropyan.yml
  mesropyan.artyom/task-7/.golangci.yaml
  mesropyan.artyom/task-7/cmd/db/main.go
  mesropyan.artyom/task-7/cmd/wifi/main.go
  mesropyan.artyom/task-7/go.mod
  mesropyan.artyom/task-7/go.sum
  mesropyan.artyom/task-7/internal/db/db_functions.go
  mesropyan.artyom/task-7/internal/db/db_functions_test.go
  mesropyan.artyom/task-7/internal/wifi/WiFi_test.go
  mesropyan.artyom/task-7/internal/wifi/wi-fi.go
  mesropyan.artyom/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#141 TASK-7
  .github/workflows/elina_klebleeva.yml
  elina.klebleeva/task-7/.golangci.yaml
  elina.klebleeva/task-7/actions_reports/lint_report.xml
  elina.klebleeva/task-7/cmd/db/main.go
  elina.klebleeva/task-7/cmd/wifi/main.go
  elina.klebleeva/task-7/go.mod
  elina.klebleeva/task-7/go.sum
  elina.klebleeva/task-7/internal/db/db_functions.go
  elina.klebleeva/task-7/internal/db/db_functions_test.go
  elina.klebleeva/task-7/internal/wifi/WiFi_test.go
  elina.klebleeva/task-7/internal/wifi/wi-fi.go
  elina.klebleeva/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#161 TASK-8
  ann.kozakova/task-8/first/go.mod
  ann.kozakova/task-8/first/main.go
  ann.kozakova/task-8/fourth/go.mod
  ann.kozakova/task-8/fourth/main.go
  ann.kozakova/task-8/fourth/wings.png
  ann.kozakova/task-8/second/add.go
  ann.kozakova/task-8/second/go.mod
  ann.kozakova/task-8/second/main.go
  ann.kozakova/task-8/second/operate.go
  ann.kozakova/task-8/third/go.mod
  ann.kozakova/task-8/third/go.sum
  ann.kozakova/task-8/third/wi-fi_test.go
  ann.kozakova/task-8/third/wifi/wi-fi.go
Labels: Approved

#156 TASK-7
  .github/workflows/mark_zheleznyakov.yml
  mark.zheleznyakov/task-7/.golangci.yml
  mark.zheleznyakov/task-7/cmd/db/main.go
  mark.zheleznyakov/task-7/cmd/wifi/main.go
  mark.zheleznyakov/task-7/go.mod
  mark.zheleznyakov/task-7/go.sum
  mark.zheleznyakov/task-7/internal/db/db_functions.go
  mark.zheleznyakov/task-7/internal/db/db_functions_test.go
  mark.zheleznyakov/task-7/internal/wifi/wi-fi.go
  mark.zheleznyakov/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#162 TASK-7
  .github/workflows/anton.piyavkin.yml
  anton.piyavkin/task-7/cmd/db/main.go
  anton.piyavkin/task-7/cmd/wifi/main.go
  anton.piyavkin/task-7/config/.golangci.yaml
  anton.piyavkin/task-7/go.mod
  anton.piyavkin/task-7/go.sum
  anton.piyavkin/task-7/internal/db/db_functions.go
  anton.piyavkin/task-7/internal/db/db_functions_test.go
  anton.piyavkin/task-7/internal/wifi/WiFi_test.go
  anton.piyavkin/task-7/internal/wifi/wi-fi.go
  anton.piyavkin/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#109 TASK-3
  erdem.istaev/task-3/cmd/service/main.go
  erdem.istaev/task-3/config/config.yaml
  erdem.istaev/task-3/go.mod
  erdem.istaev/task-3/go.sum
  erdem.istaev/task-3/internal/parser/parse_config.go
  erdem.istaev/task-3/internal/parser/parse_valute.go
  erdem.istaev/task-3/internal/sort_pkg/sort_valutes.go
  erdem.istaev/task-3/internal/writer/save_results.go
Labels: Changes required

#142 TASK-6
  maksim.kladkovoj/task-6/.golangci.yaml
  maksim.kladkovoj/task-6/cmd/db/main.go
  maksim.kladkovoj/task-6/cmd/wifi/main.go
  maksim.kladkovoj/task-6/go.mod
  maksim.kladkovoj/task-6/go.sum
  maksim.kladkovoj/task-6/internal/db/db_functions.go
  maksim.kladkovoj/task-6/internal/db/db_functions_test.go
  maksim.kladkovoj/task-6/internal/wifi/WiFi_test.go
  maksim.kladkovoj/task-6/internal/wifi/wi-fi.go
  maksim.kladkovoj/task-6/internal/wifi/wi-fi_test.go
Labels: Approved

#151 TASK-6
  gleb.madyarov/task-6/.golangci.yml
  gleb.madyarov/task-6/cmd/db/main.go
  gleb.madyarov/task-6/cmd/wifi/main.go
  gleb.madyarov/task-6/go.mod
  gleb.madyarov/task-6/go.sum
  gleb.madyarov/task-6/internal/db/db_functions.go
  gleb.madyarov/task-6/internal/db/db_functions_test.go
  gleb.madyarov/task-6/internal/wifi/WiFi_test.go
  gleb.madyarov/task-6/internal/wifi/wi-fi.go
  gleb.madyarov/task-6/internal/wifi/wi-fi_test.go
Labels: Approved

#167 TASK-7
  .github/workflows/gleb_madyarov.yml
  gleb.madyarov/task-7/.golangci.yml
  gleb.madyarov/task-7/cmd/db/main.go
  gleb.madyarov/task-7/cmd/wifi/main.go
  gleb.madyarov/task-7/go.mod
  gleb.madyarov/task-7/go.sum
  gleb.madyarov/task-7/internal/db/db_functions.go
  gleb.madyarov/task-7/internal/db/db_functions_test.go
  gleb.madyarov/task-7/internal/wifi/WiFi_test.go
  gleb.madyarov/task-7/internal/wifi/wi-fi.go
  gleb.madyarov/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#105 TASK-3
  sofia.dudkina/task-3/internal/entities/valute.go
  sofia.dudkina/task-3/internal/parser/parser.go
  sofia.dudkina/task-3/internal/writer/writer.go
Labels: Approved

#133 TASK-3
  khudyakov.gennady/task-3/cmd/service/main.go
  khudyakov.gennady/task-3/go.mod
  khudyakov.gennady/task-3/go.sum
  khudyakov.gennady/task-3/internal/config/config.go
  khudyakov.gennady/task-3/internal/currencies/currencies.go
  khudyakov.gennady/task-3/internal/io/io.go
Labels: Changes required

#128 TASK-4
  erdem.istaev/task-4/cmd/service/main.go
  erdem.istaev/task-4/go.mod
  erdem.istaev/task-4/internal/library/library.go
Labels: Approved

#159 TASK-4
  khudyakov.gennady/task-4/cmd/service/main.go
  khudyakov.gennady/task-4/go.mod
  khudyakov.gennady/task-4/internal/duplicateremover/duplicateremover.go
  khudyakov.gennady/task-4/internal/user/user.go
Labels: Approved

#144 TASK-4
  alex.udalov/task-4/cmd/service/main.go
  alex.udalov/task-4/go.mod
  alex.udalov/task-4/internal/sync_fibonacci/sync_fibonacci.go
  alex.udalov/task-4/internal/unsync_fibonacci/uncync_fibonacci.go
Labels: Approved

#140 TASK-7
  .github/workflows/danil_novkhatskiy.yml
  danil.novokhatskiy/task-7/go.mod
  danil.novokhatskiy/task-7/go.sum
  danil.novokhatskiy/task-7/golangci.yaml
  danil.novokhatskiy/task-7/internal/db/db_functions.go
  danil.novokhatskiy/task-7/internal/db/db_test.go
  danil.novokhatskiy/task-7/internal/wifi/WiFi_test.go
  danil.novokhatskiy/task-7/internal/wifi/wi-fi.go
  danil.novokhatskiy/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#178 TASK-7
  .github/workflows/erdem_istaev.yml
  erdem.istaev/task-7/.golangci.yaml
  erdem.istaev/task-7/cmd/db/main.go
  erdem.istaev/task-7/cmd/wifi/main.go
  erdem.istaev/task-7/go.mod
  erdem.istaev/task-7/go.sum
  erdem.istaev/task-7/internal/db/db_functions.go
  erdem.istaev/task-7/internal/db/db_functions_test.go
  erdem.istaev/task-7/internal/wifi/WiFi_test.go
  erdem.istaev/task-7/internal/wifi/wi-fi.go
  erdem.istaev/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#181 TASK-7
  .github/workflows/alex_udalov.yml
  alex.udalov/task-7/.golangci.yaml
  alex.udalov/task-7/cmd/db/main.go
  alex.udalov/task-7/cmd/wifi/main.go
  alex.udalov/task-7/go.mod
  alex.udalov/task-7/go.sum
  alex.udalov/task-7/internal/db/db_functions.go
  alex.udalov/task-7/internal/db/db_functions_test.go
  alex.udalov/task-7/internal/db/profilee
  alex.udalov/task-7/internal/wifi/WiFi_test.go
  alex.udalov/task-7/internal/wifi/profile
  alex.udalov/task-7/internal/wifi/wi-fi.go
  alex.udalov/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#173 TASK-7
  .github/workflows/anastasiya_soboleva.yml
  anastasiya.soboleva/task-7/.golangci.yaml
  anastasiya.soboleva/task-7/cmd/db/main.go
  anastasiya.soboleva/task-7/cmd/wifi/main.go
  anastasiya.soboleva/task-7/go.mod
  anastasiya.soboleva/task-7/go.sum
  anastasiya.soboleva/task-7/internal/db/db_functions.go
  anastasiya.soboleva/task-7/internal/db/db_functions_test.go
  anastasiya.soboleva/task-7/internal/wifi/WIFI_test.go
  anastasiya.soboleva/task-7/internal/wifi/wi-fi.go
  anastasiya.soboleva/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#169 TASK-7
  .github/workflows/sofia_dudkina.yml
  sofia.dudkina/.github/workflows/sofia_dudkina.yml
  sofia.dudkina/task-7/.golangci.yaml
  sofia.dudkina/task-7/cmd/db/main.go
  sofia.dudkina/task-7/cmd/wifi/main.go
  sofia.dudkina/task-7/go.mod
  sofia.dudkina/task-7/go.sum
  sofia.dudkina/task-7/internal/db/db_functions.go
  sofia.dudkina/task-7/internal/db/db_functions_test.go
  sofia.dudkina/task-7/internal/wifi/WiFi_test.go
  sofia.dudkina/task-7/internal/wifi/wi-fi.go
  sofia.dudkina/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#198 TASK-7
  .github/workflows/kirill_romanchuk.yml
  kirill.romanchuk/task-7/.golangci.yaml
  kirill.romanchuk/task-7/cmd/db/main.go
  kirill.romanchuk/task-7/cmd/wifi/main.go
  kirill.romanchuk/task-7/go.mod
  kirill.romanchuk/task-7/go.sum
  kirill.romanchuk/task-7/internal/db/db_functions.go
  kirill.romanchuk/task-7/internal/db/db_functions_test.go
  kirill.romanchuk/task-7/internal/wifi/WIFI_test.go
  kirill.romanchuk/task-7/internal/wifi/wi-fi.go
  kirill.romanchuk/task-7/internal/wifi/wi-fi_test.go
Labels: Approved

#187 TASK 8
  mesropyan.artyom/task-8/cmd/1/main.go
  mesropyan.artyom/task-8/cmd/2/main.go
  mesropyan.artyom/task-8/cmd/2/tags.go
  mesropyan.artyom/task-8/cmd/3/Doer_test.go
  mesropyan.artyom/task-8/cmd/3/main.go
  mesropyan.artyom/task-8/cmd/4/byte.txt
  mesropyan.artyom/task-8/cmd/4/folder/file1.txt
  mesropyan.artyom/task-8/cmd/4/folder/file2.txt
  mesropyan.artyom/task-8/cmd/4/folder/file3.txt
  mesropyan.artyom/task-8/cmd/4/main.go
  mesropyan.artyom/task-8/cmd/4/test.txt
  mesropyan.artyom/task-8/go.mod
  mesropyan.artyom/task-8/go.sum
Labels: Approved

#185 TASK-8
  gleb.madyarov/task-8/point_1/go.mod
  gleb.madyarov/task-8/point_1/main.go
  gleb.madyarov/task-8/point_2/go.mod
  gleb.madyarov/task-8/point_2/main.go
  gleb.madyarov/task-8/point_2/pro.go
  gleb.madyarov/task-8/point_3/WiFi_test.go
  gleb.madyarov/task-8/point_3/go.mod
  gleb.madyarov/task-8/point_3/go.sum
  gleb.madyarov/task-8/point_3/wi-fi.go
  gleb.madyarov/task-8/point_3/wi-fi_test.go
  gleb.madyarov/task-8/point_4/file1.hash
  gleb.madyarov/task-8/point_4/go.mod
  gleb.madyarov/task-8/point_4/main.go
  gleb.madyarov/task-8/point_4/text.txt
Labels: Approved

#186 TASK-6
  kirill.romanchuk/task-6/.golangci.yaml
  kirill.romanchuk/task-6/cmd/db/main.go
  kirill.romanchuk/task-6/cmd/wifi/main.go
  kirill.romanchuk/task-6/go.mod
  kirill.romanchuk/task-6/go.sum
  kirill.romanchuk/task-6/internal/db/db_functions.go
  kirill.romanchuk/task-6/internal/db/db_functions_test.go
  kirill.romanchuk/task-6/internal/wifi/WIFI_test.go
  kirill.romanchuk/task-6/internal/wifi/wi-fi.go
  kirill.romanchuk/task-6/internal/wifi/wi-fi_test.go
Labels: Approved

#184 TASK-8
  zhukov.gleb/task-8/first/go.mod
  zhukov.gleb/task-8/first/main.go
  zhukov.gleb/task-8/first/run.sh
  zhukov.gleb/task-8/fourth/go.mod
  zhukov.gleb/task-8/fourth/main.go
  zhukov.gleb/task-8/fourth/pic.jpg
  zhukov.gleb/task-8/second/go.mod
  zhukov.gleb/task-8/second/run.sh
  zhukov.gleb/task-8/second/tags_main.go
  zhukov.gleb/task-8/second/tags_slice.go
  zhukov.gleb/task-8/third/generate.go
  zhukov.gleb/task-8/third/go.mod
  zhukov.gleb/task-8/third/go.sum
  zhukov.gleb/task-8/third/run.sh
Labels: Approved

#193 TASK-8
  anton.piyavkin/task-8/cmd/embed/hello.txt
  anton.piyavkin/task-8/cmd/embed/main.go
  anton.piyavkin/task-8/cmd/first/main.go
  anton.piyavkin/task-8/cmd/generate/go.mod
  anton.piyavkin/task-8/cmd/generate/go.sum
  anton.piyavkin/task-8/cmd/generate/main.go
  anton.piyavkin/task-8/cmd/generate/service.go
  anton.piyavkin/task-8/cmd/tags/init.go
  anton.piyavkin/task-8/cmd/tags/main.go
  anton.piyavkin/task-8/cmd/tags/tags
  anton.piyavkin/task-8/go.mod
  anton.piyavkin/task-8/go.sum
Labels: Approved

#188 TASK-8
  andrey.kostin/task-8/cmd/build/main.go
  andrey.kostin/task-8/cmd/embed/data.json
  andrey.kostin/task-8/cmd/embed/main.go
  andrey.kostin/task-8/cmd/generate/main.go
  andrey.kostin/task-8/cmd/tags/main.go
  andrey.kostin/task-8/cmd/tags/tags-pro.go
  andrey.kostin/task-8/cmd/tags/tags-regular.go
  andrey.kostin/task-8/go.mod
  andrey.kostin/task-8/go.sum
Labels: Approved

#197 TASK-8
  sofia.dudkina/task-8/cmd/embed/main.go
  sofia.dudkina/task-8/cmd/embed/src/text1.txt
  sofia.dudkina/task-8/cmd/generate/WiFi_test.go
  sofia.dudkina/task-8/cmd/generate/wifi.go
  sofia.dudkina/task-8/cmd/service/main.go
  sofia.dudkina/task-8/cmd/service/service.exe
  sofia.dudkina/task-8/cmd/service/ssa.html
  sofia.dudkina/task-8/cmd/tags/main.go
  sofia.dudkina/task-8/cmd/tags/main_pro.go
  sofia.dudkina/task-8/go.mod
  sofia.dudkina/task-8/go.sum
Labels: Approved

#174 TASK-8
  mark.zheleznyakov/task-8/cmd/basics/main.go
  mark.zheleznyakov/task-8/cmd/tags/main.go
  mark.zheleznyakov/task-8/go.mod
  mark.zheleznyakov/task-8/go.sum
  mark.zheleznyakov/task-8/internal/feats/base.go
  mark.zheleznyakov/task-8/internal/feats/feat.go
  mark.zheleznyakov/task-8/internal/feats/find.go
  mark.zheleznyakov/task-8/internal/feats/pro.go
  mark.zheleznyakov/task-8/internal/output/JustBuyThisGoddamnThing.txt
  mark.zheleznyakov/task-8/internal/output/cli.go
  mark.zheleznyakov/task-8/internal/version/version.go
  mark.zheleznyakov/task-8/internal/version/version_pro.go
Labels: Approved

#160 TASK-6
  danil.novokhatskiy/task-6/go.mod
  danil.novokhatskiy/task-6/go.sum
  danil.novokhatskiy/task-6/golangci.yaml
  danil.novokhatskiy/task-6/internal/db/db_functions.go
  danil.novokhatskiy/task-6/internal/db/db_test.go
  danil.novokhatskiy/task-6/internal/db/mistakes.xml
  danil.novokhatskiy/task-6/internal/wifi/WiFi_test.go
  danil.novokhatskiy/task-6/internal/wifi/mistakes.xml
  danil.novokhatskiy/task-6/internal/wifi/wi-fi.go
  danil.novokhatskiy/task-6/internal/wifi/wi-fi_test.go
Labels: Approved

#172 TASK-6
  anastasiya.soboleva/task-6/.golangci.yaml
  anastasiya.soboleva/task-6/cmd/db/main.go
  anastasiya.soboleva/task-6/cmd/wifi/main.go
  anastasiya.soboleva/task-6/go.mod
  anastasiya.soboleva/task-6/go.sum
  anastasiya.soboleva/task-6/internal/db/db_functions.go
  anastasiya.soboleva/task-6/internal/db/db_functions_test.go
  anastasiya.soboleva/task-6/internal/wifi/WIFI_test.go
  anastasiya.soboleva/task-6/internal/wifi/wi-fi.go
  anastasiya.soboleva/task-6/internal/wifi/wi-fi_test.go
Labels: Changes required
